### ISSUE TITLE
Error: "No such file or directory" on rackt init

### ISSUE THREAD

**Issue by azazdeaz** [mzabriskie/rackt-cli#13]
Hi, thanks for this lib!

I don't know what did i mix up but after i call ```rackt init``` i get this error:
```sh
rackt init react-animated-topdown-zombie
/home/azazdeaz/.nvm/versions/node/v0.12.7/lib/node_modules/rackt-cli/bin/../tasks/init: line 5: /home/azazdeaz/.nvm/versions/node/v0.12.7/lib/node_modules/rackt-cli/bin/..//node_modules/.bin/originate: No such file or directory
```

Do you have a guess how should i fix this?

(I'm on Ubuntu 15.04, npm@3.3.5, and using nvm to manage node)

**Comment by mzabriskie** [comment]
Sounds like this is a problem with npm 3. I still haven't updated this project since it was released. For the time being, you can run `npm install -g rackt-cli` using npm 2.x as a workaround.

**Comment by azazdeaz** [comment]
Great, thank you!
