### ISSUE TITLE
rackt init <name> failed: node_modules/.bin/originate: No such file or directory

### ISSUE THREAD

**Issue by blesh** [mzabriskie/rackt-cli#22]
Here's what I got the first time I tried to use rackt-cli:

```shell
rackt init rackt-test

/usr/local/Cellar/nvm/0.25.4/versions/node/v5.0.0/lib/node_modules/rackt-cli/bin/../tasks/init: line 5: /usr/local/Cellar/nvm/0.25.4/versions/node/v5.0.0/lib/node_modules/rackt-cli/bin/..//node_modules/.bin/originate: No such file or directory
```

I've tried uninstalling rackt-cli and reinstalling it, but no dice.

Node version `5.0.0`
npm version `3.3.10`

**Comment by mzabriskie** [comment]
It's a problem with rackt-cli not being compatible with npm 3. I need to fix this, but haven't had time.

**Comment by blesh** [comment]
Makes sense. I'd have dug into it, but I don't have the time either. LOL. I suspect you're going to get a lot of that with a CLI tool. People who need time-savers don't often have time to contribute.
